spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:/Users/karol/Desktop/JAVA/ToDoSPRING/todo-db'

  jpa:
    hibernate:
      ddl-auto: validate
      show_sql: true
      format_sql: true

  management:
    endpoints:
      web:
        exposure:
          include: '*'

# I don't know why it does not work here - I placed keycloak config in application.properties and it works
#  keycloak:
#    auth-server-url: http://localhost:8180/auth
#    realm: ToDoApp
#    resource: 'todo-spring-client'
#    public-client: true

