spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:/Users/karol/Desktop/JAVA/ToDoSPRING/todo-db'

  jpa:
    hibernate:
      ddl-auto: validate
      show_sql: true
      format_sql: true

  management:
    endpoints:
      web:
        exposure:
          include: '*'

  keycloack:
    auth-server-url: 'http://localhost:8180/auth'
    realm: 'ToDoApp'
    resource: 'todo-spring-client'
    public-client: true